Dev (#2)
* add jobs colors

* update fonts

* change VCS prompt colors

* switch to ls -a . ls -A is for loosers

* change TZ

* ok ls -A is ok but not ls -lA

* update plugins and add more vim folder markers

* TERM settings and compression aliases

* add fzf config

* movements

* add note of inspiration

* handle linux term

* handle linux term for crouton shell

* be nice

* update fonts and tz

* fix indents

* unset TZ make nice not lag

* tab aliases for vim

* fugitive for vimdiff

* fix grepping for arch on arm

* change arm7l to all arm

* add hashivim/vim-terraform plugin

* mv docker-compose to be a .sh

* rename terraform script to .sh"

* setup a buffer bar with airline and key mappings

* add vim file autoreload on change

* move to solarized light

* add port pinger

* add editorconfig to .vimrc

* run shellcheck against duplicacy

* more pipestatus

* local latest_version

* better syntax for rmdir glob

* break up command

* cleanup command

* formatting

* testing formatting

* add openwrt sunset scripts

* add openwrt sunset scripts

* add openwrt sunset scripts

* add license

* collapse led state functions into set_led_state

* add usage info

* add error to error message

* rename function

* fix main / split up find on multiline

* trailing line

* update sunset logic

* updates

* updates

* updates

* use ping-restart and mute-replay-warnings

* add note about ping-restart

* change powerline mode, add dart sdk to path

* add pub and brew to path

* updated for tmux 2.9

* add dart and flutter to path

* add go to path

* remove quoting from variable causing redirection to fail

* update grc alias logic

* fixup grc logic

* convert youcompleteme to python3

* set ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE to fix solarized theme

* use the correct syntax for HIGHLIGHT variable

* updates

* add variable

* updates

* fix ssh agent forward and unset $ZSH

* add lsd config, switch to single [, and update tpm

* remove antigen from tree, ssh-forwarding setup right?

* add batcat

Co-authored-by: sedlund <scott.edlund+github@gmail.com>
Co-authored-by: Scott Edlund <1928989-scott.edlund@users.noreply.gitlab.com>

diff --git a/bin/duplicacy b/bin/duplicacy
--- a/bin/duplicacy
+++ b/bin/duplicacy
@@ -2,8 +2,8 @@
 #
 # Wraps duplicacy backup with auto downloading and updating functionality
 #
-# Scott Edlund <scott.edlund@gmail.com>
-# v0.4
+# Scott Edlund <sedlund@protonmail.com>
+# v0.6
 
 # Uncomment for debugging
 #DEBUG=1
@@ -11,7 +11,7 @@
 #export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 
 # Constants
-# 
+#
 # Where you want duplicacy to reside
 readonly DIR=~/bin
 # Time in seconds to wait between version checks
@@ -24,33 +24,36 @@ readonly LATEST_RELEASE='gilbertchen/duplicacy/releases/latest'
 
 # Functions
 err() {
-  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
 }
 
 update_check_file() {
-  local next_check_time=$(( ${TIME} + ${CHECK_INTERVAL} ))
+
+  local next_check_time=$(( TIME + CHECK_INTERVAL ))
   if ! echo ${next_check_time} > "${UPDATE_CHECK_FILE}" ; then
     err "Could not update ${UPDATE_CHECK_FILE} with new check interval."
     exit 1
   else
     echo "Updated check file successfully."
   fi
+
 }
 
 download() {
+
   if ! UNAME_M="$(uname -m)" ; then
     err "Unable to exec uname -m"
     exit 1
   fi
   readonly UNAME_M
-  
+
   case "${UNAME_M}" in
     x86_64) ARCH=x64 ;;
     386)    ARCH=i386 ;;
     arm*)   ARCH=arm ;;
   esac
   readonly ARCH
-  
+
   if ! UNAME="$(uname)" ; then
     err "Unable to exec uname."
     exit 1
@@ -64,7 +67,7 @@ download() {
     *MINGW* | *WIN32* | *CYGWIN*) OS='win' ;;
   esac
 
-  if [[ "${DEBUG}" ]]; then
+  if [[ -n "${DEBUG}" ]]; then
     echo "wget -qO- ${GITHUB_URL}/${LATEST_RELEASE} \
       | awk -F '\"' -v a=${OS}_${ARCH} '\$0~a{print \$2;exit}'"
   fi
@@ -72,8 +75,9 @@ download() {
   local return_codes
   DUPLICACY_PATH="$(wget -qO- ${GITHUB_URL}/${LATEST_RELEASE} \
     | awk -F '"' -v a=${OS}_${ARCH} '$0~a{print $2;exit}')"
-  return_codes=(${PIPESTATUS[*]})
+  return_codes=( "${PIPESTATUS[*]}" )
   readonly DUPLICACY_PATH
+
   if [[ "${return_codes[0]}" -ne 0 ]]; then
     err "Error issuing wget on ${GITHUB_URL}/${LATEST_RELEASE}"
     exit 1
@@ -84,9 +88,11 @@ download() {
   fi
 
   echo "Downloading Duplicacy..."
+
   if [[ "${DEBUG}" ]]; then
     echo "wget -q --show-progress -O ${GOBIN} ${GITHUB_URL}/${DUPLICACY_PATH}"
   fi
+
   if ! wget -q --show-progress -O "${GOBIN}" \
     "${GITHUB_URL}/${DUPLICACY_PATH}" ; then
     err "Error downloading ${GITHUB_URL}/${DUPLICACY_PATH} to ${GOBIN}"
@@ -99,18 +105,34 @@ download() {
   fi
 
   update_check_file
+
 }
 
 check_for_update() {
+
   echo "Checking for updates..."
 
   local return_codes
-  local current_version="v$( ${GOBIN} | grep -A1 VERSION | tail -1 \
+  local current_version
+  current_version="v$( ${GOBIN} | grep -A1 VERSION | tail -1 \
     | awk '{print $1}' )"
+  return_codes=( "${PIPESTATUS[*]}" )
 
+  if [[ "${return_codes[0]}" -ne 0 ]]; then
+    err "Error running ${GOBIN}"
+  fi
+  if [[ "${return_codes[1]}" -ne 0 ]]; then
+    err "Error running grep"
+  fi
+  if [[ "${return_codes[2]}" -ne 0 ]]; then
+    err "Error running awk"
+  fi
+
+  local latest_version
   latest_version=$(wget -qO- "${GITHUB_URL}/${LATEST_RELEASE}" \
     | awk -F "/" -v v=releases/download '$0~v{print $6;exit}')
-  return_codes=(${PIPESTATUS[*]})
+  return_codes=( "${PIPESTATUS[*]}" )
+
   if [[ "${return_codes[0]}" -ne 0 ]]; then
     err "Error running wget on ${GITHUB_URL}/${LATEST_RELEASE}"
   fi
@@ -125,28 +147,33 @@ check_for_update() {
     echo "Current version is latest..."
     update_check_file
   fi
+
 }
 
 # MAIN
 main() {
+
   if [[ ! -e "${GOBIN}" ]]; then
       download
   fi
-  
+
   if [[ -e "${UPDATE_CHECK_FILE}" ]]; then
-    local file_check_time="$(<${UPDATE_CHECK_FILE})"
+    file_check_time=$(<"${UPDATE_CHECK_FILE}")
+    readonly file_check_time
+
     if [[ "${TIME}" -gt "${file_check_time}" ]]; then
       check_for_update
     fi
-  else 
+  else
     err "Missing the UPDATE_CHECK_FILE.  If this happens repeatedly, try \
 changing the storage path."
     check_for_update
   fi
-  
+
   "${GOBIN}" "$@"
 
   exit 0
+
 }
 
 main "$@"
